-- Generated from CSV headers and postgres_etl.flat_schema; do not edit by hand.
-- Only v2/v3 tables are included (no live API or source payload archive).
BEGIN;

-- v2 datasets
CREATE TABLE IF NOT EXISTS public."etl_flat_seasons" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "name" TEXT,
    "start_year" INTEGER,
    "alias" TEXT,
    "competition_name" TEXT,
    "start_at" TIMESTAMP,
    "activation_at" TIMESTAMP,
    "end_at" TIMESTAMP,
    "champion_club_code" TEXT,
    "champion_club_name" TEXT,
    PRIMARY KEY ("competition_code", "season_code")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_clubs" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "club_code" TEXT NOT NULL,
    "name" TEXT,
    "abbreviated_name" TEXT,
    "editorial_name" TEXT,
    "tv_code" TEXT,
    "is_virtual" BOOLEAN,
    "crest_url" TEXT,
    "sponsor" TEXT,
    "permanent_name" TEXT,
    "permanent_alias" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "address" TEXT,
    "website" TEXT,
    "tickets_url" TEXT,
    "twitter_account" TEXT,
    "venue_code" TEXT,
    "city" TEXT,
    "president" TEXT,
    "phone" TEXT,
    PRIMARY KEY ("competition_code", "season_code", "club_code")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_people" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "person_key" TEXT NOT NULL,
    "person_code" TEXT,
    "name" TEXT,
    "alias" TEXT,
    "alias_raw" TEXT,
    "passport_name" TEXT,
    "passport_surname" TEXT,
    "jersey_name" TEXT,
    "abbreviated_name" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "height_cm" INTEGER,
    "weight_kg" INTEGER,
    "birth_at" TIMESTAMP,
    "birth_country_code" TEXT,
    "birth_country_name" TEXT,
    "twitter_account" TEXT,
    "instagram_account" TEXT,
    "facebook_account" TEXT,
    "is_referee" BOOLEAN,
    PRIMARY KEY ("competition_code", "season_code", "person_key")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_registrations" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "registration_key" TEXT NOT NULL,
    "person_key" TEXT NOT NULL,
    "club_code" TEXT,
    "role_code" TEXT,
    "role_name" TEXT,
    "active" BOOLEAN,
    "start_at" TIMESTAMP,
    "end_at" TIMESTAMP,
    "sort_order" INTEGER,
    "dorsal" TEXT,
    "dorsal_raw" TEXT,
    "position" INTEGER,
    "position_name" TEXT,
    "last_team" TEXT,
    "external_id" INTEGER,
    "person_name" TEXT,
    "club_name" TEXT,
    PRIMARY KEY ("competition_code", "season_code", "registration_key")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_rounds" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "round_key" TEXT NOT NULL,
    "phase_code" TEXT NOT NULL,
    "round_number" INTEGER NOT NULL,
    "round_index" INTEGER,
    "name" TEXT,
    "first_game_at" TIMESTAMP,
    "last_game_at" TIMESTAMP,
    "formatted_dates" TEXT,
    PRIMARY KEY ("competition_code", "season_code", "round_key")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_games" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "game_code" INTEGER NOT NULL,
    "source_id" TEXT,
    "identifier" TEXT,
    "phase_code" TEXT,
    "phase_name" TEXT,
    "phase_alias" TEXT,
    "phase_is_group" BOOLEAN,
    "group_id" TEXT,
    "group_name" TEXT,
    "group_raw_name" TEXT,
    "group_order" INTEGER,
    "round_number" INTEGER,
    "round_name" TEXT,
    "round_alias" TEXT,
    "scheduled_at" TIMESTAMPTZ,
    "source_date" TEXT,
    "local_date" TIMESTAMP,
    "local_time_zone_minutes" INTEGER,
    "played" BOOLEAN,
    "game_status" TEXT,
    "confirmed_date" BOOLEAN,
    "confirmed_hour" BOOLEAN,
    "local_club_code" TEXT,
    "local_club_name" TEXT,
    "local_club_abbreviated_name" TEXT,
    "local_club_tv_code" TEXT,
    "road_club_code" TEXT,
    "road_club_name" TEXT,
    "road_club_abbreviated_name" TEXT,
    "road_club_tv_code" TEXT,
    "local_score" INTEGER,
    "road_score" INTEGER,
    "local_standings_score" INTEGER,
    "road_standings_score" INTEGER,
    "match_winner_club_code" TEXT,
    "champion_club_code" TEXT,
    "champion_club_name" TEXT,
    "audience" INTEGER,
    "audience_confirmed" BOOLEAN,
    "venue_code" TEXT,
    "venue_name" TEXT,
    "venue_capacity" INTEGER,
    "venue_address" TEXT,
    "venue_active" BOOLEAN,
    "venue_notes" TEXT,
    "is_neutral_venue" BOOLEAN,
    "social_feed" TEXT,
    "operations_code" TEXT,
    PRIMARY KEY ("competition_code", "season_code", "game_code")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_game_officials" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "game_code" INTEGER NOT NULL,
    "official_number" INTEGER NOT NULL,
    "official_code" TEXT,
    "name" TEXT,
    "alias" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "active" BOOLEAN,
    "image_vertical_small" TEXT,
    PRIMARY KEY ("competition_code", "season_code", "game_code", "official_number")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_game_period_scores" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "game_code" INTEGER NOT NULL,
    "side" TEXT NOT NULL,
    "period_number" INTEGER NOT NULL,
    "score" INTEGER,
    PRIMARY KEY ("competition_code", "season_code", "game_code", "side", "period_number")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_game_player_stats" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "game_code" INTEGER NOT NULL,
    "side" TEXT NOT NULL,
    "person_key" TEXT NOT NULL,
    "club_code" TEXT,
    "person_name" TEXT,
    "club_name" TEXT,
    "player_type_code" TEXT,
    "registration_active" BOOLEAN,
    "registration_start_at" TIMESTAMP,
    "registration_end_at" TIMESTAMP,
    "position" INTEGER,
    "position_name" TEXT,
    "dorsal" TEXT,
    "external_id" INTEGER,
    "headshot_url" TEXT,
    "points" NUMERIC,
    "time_played" NUMERIC,
    "valuation" NUMERIC,
    "field_goals_made2" NUMERIC,
    "field_goals_attempted2" NUMERIC,
    "field_goals_made3" NUMERIC,
    "field_goals_attempted3" NUMERIC,
    "free_throws_made" NUMERIC,
    "free_throws_attempted" NUMERIC,
    "field_goals_made_total" NUMERIC,
    "field_goals_attempted_total" NUMERIC,
    "accuracy_made" NUMERIC,
    "accuracy_attempted" NUMERIC,
    "total_rebounds" NUMERIC,
    "defensive_rebounds" NUMERIC,
    "offensive_rebounds" NUMERIC,
    "assistances" NUMERIC,
    "steals" NUMERIC,
    "turnovers" NUMERIC,
    "blocks_favour" NUMERIC,
    "blocks_against" NUMERIC,
    "fouls_commited" NUMERIC,
    "fouls_received" NUMERIC,
    "plus_minus" NUMERIC,
    "started" BOOLEAN,
    "started_alt" BOOLEAN,
    PRIMARY KEY ("competition_code", "season_code", "game_code", "side", "person_key")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_game_team_stats" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "game_code" INTEGER NOT NULL,
    "side" TEXT NOT NULL,
    "stats_kind" TEXT NOT NULL,
    "coach_code" TEXT,
    "coach_name" TEXT,
    "points" NUMERIC,
    "time_played" NUMERIC,
    "valuation" NUMERIC,
    "field_goals_made2" NUMERIC,
    "field_goals_attempted2" NUMERIC,
    "field_goals_made3" NUMERIC,
    "field_goals_attempted3" NUMERIC,
    "free_throws_made" NUMERIC,
    "free_throws_attempted" NUMERIC,
    "field_goals_made_total" NUMERIC,
    "field_goals_attempted_total" NUMERIC,
    "accuracy_made" NUMERIC,
    "accuracy_attempted" NUMERIC,
    "total_rebounds" NUMERIC,
    "defensive_rebounds" NUMERIC,
    "offensive_rebounds" NUMERIC,
    "assistances" NUMERIC,
    "steals" NUMERIC,
    "turnovers" NUMERIC,
    "blocks_favour" NUMERIC,
    "blocks_against" NUMERIC,
    "fouls_commited" NUMERIC,
    "fouls_received" NUMERIC,
    "plus_minus" NUMERIC,
    PRIMARY KEY ("competition_code", "season_code", "game_code", "side", "stats_kind")
);

-- v3 datasets
CREATE TABLE IF NOT EXISTS public."etl_flat_season_stats_traditional" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "phase_code" TEXT NOT NULL,
    "mode" TEXT NOT NULL,
    "entry_ordinal" INTEGER NOT NULL,
    "person_key" TEXT NOT NULL,
    "club_code" TEXT,
    "player_name" TEXT,
    "player_age" INTEGER,
    "player_image_url" TEXT,
    "club_name" TEXT,
    "club_tv_codes" TEXT,
    "club_image_url" TEXT,
    "player_ranking" INTEGER,
    "games_played" NUMERIC,
    "games_started" NUMERIC,
    "minutes_played" NUMERIC,
    "points_scored" NUMERIC,
    "two_pointers_made" NUMERIC,
    "two_pointers_attempted" NUMERIC,
    "two_pointers_percentage" NUMERIC,
    "three_pointers_made" NUMERIC,
    "three_pointers_attempted" NUMERIC,
    "three_pointers_percentage" NUMERIC,
    "free_throws_made" NUMERIC,
    "free_throws_attempted" NUMERIC,
    "free_throws_percentage" NUMERIC,
    "offensive_rebounds" NUMERIC,
    "defensive_rebounds" NUMERIC,
    "total_rebounds" NUMERIC,
    "assists" NUMERIC,
    "steals" NUMERIC,
    "turnovers" NUMERIC,
    "blocks" NUMERIC,
    "blocks_against" NUMERIC,
    "fouls_commited" NUMERIC,
    "fouls_drawn" NUMERIC,
    "pir" NUMERIC,
    PRIMARY KEY ("competition_code", "season_code", "phase_code", "mode", "entry_ordinal")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_season_stats_advanced" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "phase_code" TEXT NOT NULL,
    "mode" TEXT NOT NULL,
    "entry_ordinal" INTEGER NOT NULL,
    "person_key" TEXT NOT NULL,
    "club_code" TEXT,
    "player_name" TEXT,
    "player_age" INTEGER,
    "player_image_url" TEXT,
    "club_name" TEXT,
    "club_tv_codes" TEXT,
    "club_image_url" TEXT,
    "player_ranking" INTEGER,
    "games_played" NUMERIC,
    "minutes_played" NUMERIC,
    "effective_field_goal_percentage" NUMERIC,
    "true_shooting_percentage" NUMERIC,
    "offensive_rebounds_percentage" NUMERIC,
    "defensive_rebounds_percentage" NUMERIC,
    "rebounds_percentage" NUMERIC,
    "assists_to_turnovers_ratio" NUMERIC,
    "assists_ratio" NUMERIC,
    "turnovers_ratio" NUMERIC,
    "two_point_attempts_ratio" NUMERIC,
    "three_point_attempts_ratio" NUMERIC,
    "free_throws_rate" NUMERIC,
    "possesions" NUMERIC,
    PRIMARY KEY ("competition_code", "season_code", "phase_code", "mode", "entry_ordinal")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_season_stats_scoring" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "phase_code" TEXT NOT NULL,
    "mode" TEXT NOT NULL,
    "entry_ordinal" INTEGER NOT NULL,
    "person_key" TEXT NOT NULL,
    "club_code" TEXT,
    "player_name" TEXT,
    "player_age" INTEGER,
    "player_image_url" TEXT,
    "club_name" TEXT,
    "club_tv_codes" TEXT,
    "club_image_url" TEXT,
    "player_ranking" INTEGER,
    "games_played" NUMERIC,
    "games_started" NUMERIC,
    "two_point_attempts_share" NUMERIC,
    "three_point_attempts_share" NUMERIC,
    "free_throws_attempts_share" NUMERIC,
    "two_pointers_made_share" NUMERIC,
    "three_pointers_made_share" NUMERIC,
    "free_throws_made_share" NUMERIC,
    "two_point_rate" NUMERIC,
    "three_point_rate" NUMERIC,
    "points_from_two_pointers_percentage" NUMERIC,
    "points_from_three_pointers_percentage" NUMERIC,
    "points_from_free_throws_percentage" NUMERIC,
    PRIMARY KEY ("competition_code", "season_code", "phase_code", "mode", "entry_ordinal")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_season_stats_misc" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "phase_code" TEXT NOT NULL,
    "mode" TEXT NOT NULL,
    "entry_ordinal" INTEGER NOT NULL,
    "person_key" TEXT NOT NULL,
    "club_code" TEXT,
    "player_name" TEXT,
    "player_age" INTEGER,
    "player_image_url" TEXT,
    "club_name" TEXT,
    "club_tv_codes" TEXT,
    "club_image_url" TEXT,
    "player_ranking" INTEGER,
    "games_played" NUMERIC,
    "games_started" NUMERIC,
    "wins" NUMERIC,
    "losses" NUMERIC,
    "minutes_played" NUMERIC,
    "double_doubles" NUMERIC,
    "triple_doubles" NUMERIC,
    PRIMARY KEY ("competition_code", "season_code", "phase_code", "mode", "entry_ordinal")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_standings_basicstandings" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "phase_code" TEXT NOT NULL,
    "round_number" INTEGER NOT NULL,
    "club_code" TEXT NOT NULL,
    "club_name" TEXT,
    "club_tv_code" TEXT,
    "group_name" TEXT,
    "position" INTEGER,
    "position_change" TEXT,
    "games_played" INTEGER,
    "games_won" INTEGER,
    "games_lost" INTEGER,
    "qualified" BOOLEAN,
    "win_percentage" NUMERIC,
    "points_difference" INTEGER,
    "points_for" INTEGER,
    "points_against" INTEGER,
    "home_record" TEXT,
    "away_record" TEXT,
    "neutral_record" TEXT,
    "overtime_record" TEXT,
    "last_ten_record" TEXT,
    PRIMARY KEY ("competition_code", "season_code", "phase_code", "round_number", "club_code")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_standings_calendarstandings" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "phase_code" TEXT NOT NULL,
    "round_number" INTEGER NOT NULL,
    "club_code" TEXT NOT NULL,
    "club_name" TEXT,
    "club_tv_code" TEXT,
    "group_name" TEXT,
    "position" INTEGER,
    "position_change" TEXT,
    "games_played" INTEGER,
    "games_won" INTEGER,
    "games_lost" INTEGER,
    "qualified" BOOLEAN,
    PRIMARY KEY ("competition_code", "season_code", "phase_code", "round_number", "club_code")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_standings_streaks" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "phase_code" TEXT NOT NULL,
    "round_number" INTEGER NOT NULL,
    "club_code" TEXT NOT NULL,
    "club_name" TEXT,
    "club_tv_code" TEXT,
    "group_name" TEXT,
    "position" INTEGER,
    "position_change" TEXT,
    "games_played" INTEGER,
    "games_won" INTEGER,
    "games_lost" INTEGER,
    "qualified" BOOLEAN,
    "home_record" TEXT,
    "away_record" TEXT,
    "last10" TEXT,
    "home_last5" TEXT,
    "away_last5" TEXT,
    "longest_wins_streak_current_season" INTEGER,
    "longest_loses_streak_current_season" INTEGER,
    "longest_wins_streak_any_season" INTEGER,
    "longest_loses_streak_any_season" INTEGER,
    PRIMARY KEY ("competition_code", "season_code", "phase_code", "round_number", "club_code")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_standings_aheadbehind" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "phase_code" TEXT NOT NULL,
    "round_number" INTEGER NOT NULL,
    "club_code" TEXT NOT NULL,
    "club_name" TEXT,
    "club_tv_code" TEXT,
    "group_name" TEXT,
    "position" INTEGER,
    "position_change" TEXT,
    "games_played" INTEGER,
    "games_won" INTEGER,
    "games_lost" INTEGER,
    "qualified" BOOLEAN,
    "wins_percentage" NUMERIC,
    "quater1_ahead" TEXT,
    "quater1_behind" TEXT,
    "quater1_tied" TEXT,
    "half1_ahead" TEXT,
    "half1_behind" TEXT,
    "half1_tied" TEXT,
    "quater3_ahead" TEXT,
    "quater3_behind" TEXT,
    "quater3_tied" TEXT,
    PRIMARY KEY ("competition_code", "season_code", "phase_code", "round_number", "club_code")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_standings_margins" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "phase_code" TEXT NOT NULL,
    "round_number" INTEGER NOT NULL,
    "club_code" TEXT NOT NULL,
    "club_name" TEXT,
    "club_tv_code" TEXT,
    "group_name" TEXT,
    "position" INTEGER,
    "position_change" TEXT,
    "games_played" INTEGER,
    "games_won" INTEGER,
    "games_lost" INTEGER,
    "qualified" BOOLEAN,
    "point_difference1to5" TEXT,
    "point_difference6to10" TEXT,
    "point_difference11to15" TEXT,
    "point_difference_more_than15" TEXT,
    "rebounds" TEXT,
    "assists" TEXT,
    "blocks" TEXT,
    "three_pointers" TEXT,
    "two_pointers" TEXT,
    "free_throws" TEXT,
    PRIMARY KEY ("competition_code", "season_code", "phase_code", "round_number", "club_code")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_standings_calendar_streaks" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "phase_code" TEXT NOT NULL,
    "round_number" INTEGER NOT NULL,
    "club_code" TEXT NOT NULL,
    "streak_ordinal" INTEGER NOT NULL,
    "start_at" TIMESTAMP,
    "end_at" TIMESTAMP,
    "win_loss_record" TEXT,
    PRIMARY KEY ("competition_code", "season_code", "phase_code", "round_number", "club_code", "streak_ordinal")
);

CREATE TABLE IF NOT EXISTS public."etl_flat_standings_basic_form" (
    "competition_code" TEXT NOT NULL,
    "season_code" TEXT NOT NULL,
    "phase_code" TEXT NOT NULL,
    "round_number" INTEGER NOT NULL,
    "club_code" TEXT NOT NULL,
    "result_ordinal" INTEGER NOT NULL,
    "result" TEXT,
    PRIMARY KEY ("competition_code", "season_code", "phase_code", "round_number", "club_code", "result_ordinal")
);

COMMIT;
