import { boolean, integer, jsonb, numeric, pgTable, primaryKey, text, timestamp } from "drizzle-orm/pg-core";

export const seasons = pgTable(
  "app_seasons",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    name: text("name"),
    startYear: integer("start_year"),
    competitionName: text("competition_name"),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode] })],
);

export const rounds = pgTable(
  "app_rounds",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    roundKey: text("round_key").notNull(),
    phaseCode: text("phase_code").notNull(),
    roundNumber: integer("round_number").notNull(),
    roundIndex: integer("round_index"),
    name: text("name"),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.roundKey] })],
);

export const games = pgTable(
  "app_games",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    gameCode: integer("game_code").notNull(),
    sourceId: text("source_id"),
    identifier: text("identifier"),
    phaseCode: text("phase_code"),
    phaseName: text("phase_name"),
    groupId: text("group_id"),
    groupName: text("group_name"),
    roundNumber: integer("round_number"),
    roundName: text("round_name"),
    scheduledAt: timestamp("scheduled_at", { withTimezone: true }),
    played: boolean("played"),
    gameStatus: text("game_status"),
    localClubCode: text("local_club_code"),
    localClubName: text("local_club_name"),
    localClubAbbreviatedName: text("local_club_abbreviated_name"),
    roadClubCode: text("road_club_code"),
    roadClubName: text("road_club_name"),
    roadClubAbbreviatedName: text("road_club_abbreviated_name"),
    localScore: integer("local_score"),
    roadScore: integer("road_score"),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.gameCode] })],
);

export const clubs = pgTable(
  "app_clubs",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    clubCode: text("club_code").notNull(),
    name: text("name"),
    abbreviatedName: text("abbreviated_name"),
    countryCode: text("country_code"),
    crestUrl: text("crest_url"),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.clubCode] })],
);

export const people = pgTable(
  "app_people",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    personKey: text("person_key").notNull(),
    name: text("name"),
    jerseyName: text("jersey_name"),
    countryCode: text("country_code"),
    heightCm: integer("height_cm"),
    isReferee: boolean("is_referee"),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.personKey] })],
);

export const registrations = pgTable(
  "app_registrations",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    registrationKey: text("registration_key").notNull(),
    personKey: text("person_key").notNull(),
    clubCode: text("club_code"),
    roleCode: text("role_code"),
    roleName: text("role_name"),
    active: boolean("active"),
    sortOrder: integer("sort_order"),
    dorsal: text("dorsal"),
    positionName: text("position_name"),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.registrationKey] })],
);

function boxMeasureColumns() {
  return {
    points: numeric("points"),
    timePlayed: numeric("time_played"),
    valuation: numeric("valuation"),
    fieldGoalsMade2: numeric("field_goals_made2"),
    fieldGoalsAttempted2: numeric("field_goals_attempted2"),
    fieldGoalsMade3: numeric("field_goals_made3"),
    fieldGoalsAttempted3: numeric("field_goals_attempted3"),
    freeThrowsMade: numeric("free_throws_made"),
    freeThrowsAttempted: numeric("free_throws_attempted"),
    fieldGoalsMadeTotal: numeric("field_goals_made_total"),
    fieldGoalsAttemptedTotal: numeric("field_goals_attempted_total"),
    accuracyMade: numeric("accuracy_made"),
    accuracyAttempted: numeric("accuracy_attempted"),
    totalRebounds: numeric("total_rebounds"),
    defensiveRebounds: numeric("defensive_rebounds"),
    offensiveRebounds: numeric("offensive_rebounds"),
    assistances: numeric("assistances"),
    steals: numeric("steals"),
    turnovers: numeric("turnovers"),
    blocksFavour: numeric("blocks_favour"),
    blocksAgainst: numeric("blocks_against"),
    foulsCommited: numeric("fouls_commited"),
    foulsReceived: numeric("fouls_received"),
    plusMinus: numeric("plus_minus"),
  };
}

export const gamePeriodScores = pgTable(
  "app_game_period_scores",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    gameCode: integer("game_code").notNull(),
    side: text("side").notNull(),
    periodNumber: integer("period_number").notNull(),
    score: integer("score"),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.gameCode, table.side, table.periodNumber] })],
);

export const playByPlay = pgTable(
  "app_play_by_play",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    gameCode: integer("game_code").notNull(),
    period: text("period").notNull(),
    eventOrdinal: integer("event_ordinal").notNull(),
    playNumber: integer("play_number"),
    clubCode: text("club_code"),
    personCode: text("person_code"),
    playType: text("play_type"),
    playerName: text("player_name"),
    teamName: text("team_name"),
    dorsal: text("dorsal"),
    minute: integer("minute"),
    markerTime: text("marker_time"),
    pointsA: integer("points_a"),
    pointsB: integer("points_b"),
    playInfo: text("play_info"),
  },
  (table) => [
    primaryKey({ columns: [table.competitionCode, table.seasonCode, table.gameCode, table.period, table.eventOrdinal] }),
  ],
);

export const gameTeamStats = pgTable(
  "app_game_team_stats",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    gameCode: integer("game_code").notNull(),
    side: text("side").notNull(),
    statsKind: text("stats_kind").notNull(),
    coachCode: text("coach_code"),
    coachName: text("coach_name"),
    ...boxMeasureColumns(),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.gameCode, table.side, table.statsKind] })],
);

export const gamePlayerStats = pgTable(
  "app_game_player_stats",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    gameCode: integer("game_code").notNull(),
    side: text("side").notNull(),
    personKey: text("person_key").notNull(),
    clubCode: text("club_code"),
    personName: text("person_name"),
    clubName: text("club_name"),
    playerTypeCode: text("player_type_code"),
    registrationActive: boolean("registration_active"),
    position: integer("position"),
    positionName: text("position_name"),
    dorsal: text("dorsal"),
    headshotUrl: text("headshot_url"),
    started: boolean("started"),
    startedAlt: boolean("started_alt"),
    ...boxMeasureColumns(),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.gameCode, table.side, table.personKey] })],
);

export const teamSeasonStats = pgTable(
  "app_team_season_stats",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    phaseCode: text("phase_code").notNull(),
    clubCode: text("club_code").notNull(),
    clubName: text("club_name"),
    gamesPlayed: integer("games_played").notNull(),
    ownPoints: numeric("own_points"),
    ownFieldGoalsMade2: numeric("own_field_goals_made2"),
    ownFieldGoalsAttempted2: numeric("own_field_goals_attempted2"),
    ownFieldGoalsMade3: numeric("own_field_goals_made3"),
    ownFieldGoalsAttempted3: numeric("own_field_goals_attempted3"),
    ownFreeThrowsMade: numeric("own_free_throws_made"),
    ownFreeThrowsAttempted: numeric("own_free_throws_attempted"),
    ownFieldGoalsMadeTotal: numeric("own_field_goals_made_total"),
    ownFieldGoalsAttemptedTotal: numeric("own_field_goals_attempted_total"),
    ownTotalRebounds: numeric("own_total_rebounds"),
    ownDefensiveRebounds: numeric("own_defensive_rebounds"),
    ownOffensiveRebounds: numeric("own_offensive_rebounds"),
    ownAssistances: numeric("own_assistances"),
    ownSteals: numeric("own_steals"),
    ownTurnovers: numeric("own_turnovers"),
    ownBlocksFavour: numeric("own_blocks_favour"),
    ownBlocksAgainst: numeric("own_blocks_against"),
    ownFoulsCommited: numeric("own_fouls_commited"),
    ownFoulsReceived: numeric("own_fouls_received"),
    ownValuation: numeric("own_valuation"),
    oppPoints: numeric("opp_points"),
    oppFieldGoalsMade2: numeric("opp_field_goals_made2"),
    oppFieldGoalsAttempted2: numeric("opp_field_goals_attempted2"),
    oppFieldGoalsMade3: numeric("opp_field_goals_made3"),
    oppFieldGoalsAttempted3: numeric("opp_field_goals_attempted3"),
    oppFreeThrowsMade: numeric("opp_free_throws_made"),
    oppFreeThrowsAttempted: numeric("opp_free_throws_attempted"),
    oppFieldGoalsMadeTotal: numeric("opp_field_goals_made_total"),
    oppFieldGoalsAttemptedTotal: numeric("opp_field_goals_attempted_total"),
    oppTotalRebounds: numeric("opp_total_rebounds"),
    oppDefensiveRebounds: numeric("opp_defensive_rebounds"),
    oppOffensiveRebounds: numeric("opp_offensive_rebounds"),
    oppAssistances: numeric("opp_assistances"),
    oppSteals: numeric("opp_steals"),
    oppTurnovers: numeric("opp_turnovers"),
    oppBlocksFavour: numeric("opp_blocks_favour"),
    oppBlocksAgainst: numeric("opp_blocks_against"),
    oppFoulsCommited: numeric("opp_fouls_commited"),
    oppFoulsReceived: numeric("opp_fouls_received"),
    oppValuation: numeric("opp_valuation"),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.phaseCode, table.clubCode] })],
);

export const postseasonSeries = pgTable(
  "app_postseason_series",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    phaseCode: text("phase_code").notNull(),
    clubACode: text("club_a_code").notNull(),
    clubBCode: text("club_b_code").notNull(),
    clubAName: text("club_a_name"),
    clubBName: text("club_b_name"),
    gamesPlayed: integer("games_played"),
    clubAWins: integer("club_a_wins"),
    clubBWins: integer("club_b_wins"),
    winnerClubCode: text("winner_club_code"),
    games: jsonb("games").notNull().$type<{
      gameCode: number;
      roundNumber: number | null;
      scheduledAt: string | null;
      localClubCode: string | null;
      roadClubCode: string | null;
      localScore: number | null;
      roadScore: number | null;
      winnerClubCode: string | null;
    }[]>(),
  },
  (table) => [
    primaryKey({ columns: [table.competitionCode, table.seasonCode, table.phaseCode, table.clubACode, table.clubBCode] }),
  ],
);

export const coverageSeasons = pgTable(
  "app_coverage_seasons",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    items: jsonb("items").notNull(),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode] })],
);

export const coverageGames = pgTable(
  "app_coverage_games",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    gameCode: integer("game_code").notNull(),
    items: jsonb("items").notNull(),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.gameCode] })],
);

export const standings = pgTable(
  "app_standings",
  {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    phaseCode: text("phase_code").notNull(),
    roundNumber: integer("round_number").notNull(),
    clubCode: text("club_code").notNull(),
    clubName: text("club_name"),
    clubTvCode: text("club_tv_code"),
    crestUrl: text("crest_url"),
    groupName: text("group_name"),
    basicPosition: integer("basic_position"),
    basicPositionChange: text("basic_position_change"),
    basicGamesPlayed: integer("basic_games_played"),
    basicGamesWon: integer("basic_games_won"),
    basicGamesLost: integer("basic_games_lost"),
    basicQualified: boolean("basic_qualified"),
    basicWinPercentage: numeric("basic_win_percentage"),
    basicPointsDifference: integer("basic_points_difference"),
    basicPointsFor: integer("basic_points_for"),
    basicPointsAgainst: integer("basic_points_against"),
    basicHomeRecord: text("basic_home_record"),
    basicAwayRecord: text("basic_away_record"),
    basicNeutralRecord: text("basic_neutral_record"),
    basicOvertimeRecord: text("basic_overtime_record"),
    basicLastTenRecord: text("basic_last_ten_record"),
    calendarPosition: integer("calendar_position"),
    calendarPositionChange: text("calendar_position_change"),
    calendarGamesPlayed: integer("calendar_games_played"),
    calendarGamesWon: integer("calendar_games_won"),
    calendarGamesLost: integer("calendar_games_lost"),
    calendarQualified: boolean("calendar_qualified"),
    streaksPosition: integer("streaks_position"),
    streaksPositionChange: text("streaks_position_change"),
    streaksGamesPlayed: integer("streaks_games_played"),
    streaksGamesWon: integer("streaks_games_won"),
    streaksGamesLost: integer("streaks_games_lost"),
    streaksQualified: boolean("streaks_qualified"),
    streaksHomeRecord: text("streaks_home_record"),
    streaksAwayRecord: text("streaks_away_record"),
    streaksLast10: text("streaks_last10"),
    streaksHomeLast5: text("streaks_home_last5"),
    streaksAwayLast5: text("streaks_away_last5"),
    streaksLongestWinStreakCurrentSeason: integer("streaks_longest_win_streak_current_season"),
    streaksLongestLoseStreakCurrentSeason: integer("streaks_longest_lose_streak_current_season"),
    streaksLongestWinStreakAnySeason: integer("streaks_longest_win_streak_any_season"),
    streaksLongestLoseStreakAnySeason: integer("streaks_longest_lose_streak_any_season"),
    aheadBehindPosition: integer("ahead_behind_position"),
    aheadBehindPositionChange: text("ahead_behind_position_change"),
    aheadBehindGamesPlayed: integer("ahead_behind_games_played"),
    aheadBehindGamesWon: integer("ahead_behind_games_won"),
    aheadBehindGamesLost: integer("ahead_behind_games_lost"),
    aheadBehindQualified: boolean("ahead_behind_qualified"),
    aheadBehindWinsPercentage: numeric("ahead_behind_wins_percentage"),
    aheadBehindQuarter1Ahead: text("ahead_behind_quarter1_ahead"),
    aheadBehindQuarter1Behind: text("ahead_behind_quarter1_behind"),
    aheadBehindQuarter1Tied: text("ahead_behind_quarter1_tied"),
    aheadBehindHalf1Ahead: text("ahead_behind_half1_ahead"),
    aheadBehindHalf1Behind: text("ahead_behind_half1_behind"),
    aheadBehindHalf1Tied: text("ahead_behind_half1_tied"),
    aheadBehindQuarter3Ahead: text("ahead_behind_quarter3_ahead"),
    aheadBehindQuarter3Behind: text("ahead_behind_quarter3_behind"),
    aheadBehindQuarter3Tied: text("ahead_behind_quarter3_tied"),
    marginsPosition: integer("margins_position"),
    marginsPositionChange: text("margins_position_change"),
    marginsGamesPlayed: integer("margins_games_played"),
    marginsGamesWon: integer("margins_games_won"),
    marginsGamesLost: integer("margins_games_lost"),
    marginsQualified: boolean("margins_qualified"),
    marginsPointDifference1To5: text("margins_point_difference_1_to_5"),
    marginsPointDifference6To10: text("margins_point_difference_6_to_10"),
    marginsPointDifference11To15: text("margins_point_difference_11_to_15"),
    marginsPointDifferenceMoreThan15: text("margins_point_difference_more_than_15"),
    marginsRebounds: text("margins_rebounds"),
    marginsAssists: text("margins_assists"),
    marginsBlocks: text("margins_blocks"),
    marginsThreePointers: text("margins_three_pointers"),
    marginsTwoPointers: text("margins_two_pointers"),
    marginsFreeThrows: text("margins_free_throws"),
    form: jsonb("form").$type<{ resultOrdinal: number; result: string | null }[]>(),
    streakHistory: jsonb("streak_history").$type<
      { streakOrdinal: number; startAt: string | null; endAt: string | null; winLossRecord: string | null }[]
    >(),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.phaseCode, table.roundNumber, table.clubCode] })],
);

function statsIdentityColumns() {
  return {
    competitionCode: text("competition_code").notNull(),
    seasonCode: text("season_code").notNull(),
    phaseCode: text("phase_code").notNull(),
    mode: text("mode").notNull(),
    entryOrdinal: integer("entry_ordinal").notNull(),
    personKey: text("person_key").notNull(),
    clubCode: text("club_code"),
    playerName: text("player_name"),
    playerAge: integer("player_age"),
    playerImageUrl: text("player_image_url"),
    clubName: text("club_name"),
    clubTvCodes: text("club_tv_codes"),
    clubImageUrl: text("club_image_url"),
    playerRanking: integer("player_ranking"),
  };
}

export const seasonStatsTraditional = pgTable(
  "app_season_stats_traditional",
  {
    ...statsIdentityColumns(),
    gamesPlayed: numeric("games_played"),
    gamesStarted: numeric("games_started"),
    minutesPlayed: numeric("minutes_played"),
    pointsScored: numeric("points_scored"),
    twoPointersMade: numeric("two_pointers_made"),
    twoPointersAttempted: numeric("two_pointers_attempted"),
    twoPointersPercentage: numeric("two_pointers_percentage"),
    threePointersMade: numeric("three_pointers_made"),
    threePointersAttempted: numeric("three_pointers_attempted"),
    threePointersPercentage: numeric("three_pointers_percentage"),
    freeThrowsMade: numeric("free_throws_made"),
    freeThrowsAttempted: numeric("free_throws_attempted"),
    freeThrowsPercentage: numeric("free_throws_percentage"),
    offensiveRebounds: numeric("offensive_rebounds"),
    defensiveRebounds: numeric("defensive_rebounds"),
    totalRebounds: numeric("total_rebounds"),
    assists: numeric("assists"),
    steals: numeric("steals"),
    turnovers: numeric("turnovers"),
    blocks: numeric("blocks"),
    blocksAgainst: numeric("blocks_against"),
    foulsCommited: numeric("fouls_commited"),
    foulsDrawn: numeric("fouls_drawn"),
    pir: numeric("pir"),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.phaseCode, table.mode, table.entryOrdinal] })],
);

export const seasonStatsAdvanced = pgTable(
  "app_season_stats_advanced",
  {
    ...statsIdentityColumns(),
    gamesPlayed: numeric("games_played"),
    minutesPlayed: numeric("minutes_played"),
    effectiveFieldGoalPercentage: numeric("effective_field_goal_percentage"),
    trueShootingPercentage: numeric("true_shooting_percentage"),
    offensiveReboundsPercentage: numeric("offensive_rebounds_percentage"),
    defensiveReboundsPercentage: numeric("defensive_rebounds_percentage"),
    reboundsPercentage: numeric("rebounds_percentage"),
    assistsToTurnoversRatio: numeric("assists_to_turnovers_ratio"),
    assistsRatio: numeric("assists_ratio"),
    turnoversRatio: numeric("turnovers_ratio"),
    twoPointAttemptsRatio: numeric("two_point_attempts_ratio"),
    threePointAttemptsRatio: numeric("three_point_attempts_ratio"),
    freeThrowsRate: numeric("free_throws_rate"),
    possessions: numeric("possesions"),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.phaseCode, table.mode, table.entryOrdinal] })],
);

export const seasonStatsScoring = pgTable(
  "app_season_stats_scoring",
  {
    ...statsIdentityColumns(),
    gamesPlayed: numeric("games_played"),
    gamesStarted: numeric("games_started"),
    twoPointAttemptsShare: numeric("two_point_attempts_share"),
    threePointAttemptsShare: numeric("three_point_attempts_share"),
    freeThrowsAttemptsShare: numeric("free_throws_attempts_share"),
    twoPointersMadeShare: numeric("two_pointers_made_share"),
    threePointersMadeShare: numeric("three_pointers_made_share"),
    freeThrowsMadeShare: numeric("free_throws_made_share"),
    twoPointRate: numeric("two_point_rate"),
    threePointRate: numeric("three_point_rate"),
    pointsFromTwoPointersPercentage: numeric("points_from_two_pointers_percentage"),
    pointsFromThreePointersPercentage: numeric("points_from_three_pointers_percentage"),
    pointsFromFreeThrowsPercentage: numeric("points_from_free_throws_percentage"),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.phaseCode, table.mode, table.entryOrdinal] })],
);

export const seasonStatsMisc = pgTable(
  "app_season_stats_misc",
  {
    ...statsIdentityColumns(),
    gamesPlayed: numeric("games_played"),
    gamesStarted: numeric("games_started"),
    wins: numeric("wins"),
    losses: numeric("losses"),
    minutesPlayed: numeric("minutes_played"),
    doubleDoubles: numeric("double_doubles"),
    tripleDoubles: numeric("triple_doubles"),
  },
  (table) => [primaryKey({ columns: [table.competitionCode, table.seasonCode, table.phaseCode, table.mode, table.entryOrdinal] })],
);
